image: node:14

test_production:
  image: node:14
  stage: test
  only:
  - master
  script:
  - cd ./functions/fetchDesserts; npm install
  - cd ../Shell\ scripts; chmod u+x ./2-compile.sh; ./2-compile.sh fetchDesserts

deploy_production:
  stage: deploy
  only:
  - master
  script:
  - curl https://sdk.cloud.google.com > install.sh; chmod u+x ./install.sh; ./install.sh --disable-prompts
  - source /root/google-cloud-sdk/completion.bash.inc; source /root/google-cloud-sdk/path.bash.inc
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud config set project $PROJECT_ID
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - cd ./functions/Shell\ scripts; chmod u+x ./4-deploy-silent.sh; ./4-deploy-silent.sh fetchDesserts
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
