image: node:14

test_production:
  image: node:14
  stage: test
  only:
  - production
  script:
  - cd ./functions/Shell\ scripts
  - chmod u+x ./2-compile.sh
  - ./2-compile.sh fetchDesserts

deploy_production:
  stage: deploy
  environment: Production
  only:
  - production
  script:
  - cd ./functions/fetchDesserts
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud functions deploy fetchDesserts --entry-point fetchDesserts --runtime nodejs14 --trigger-http --allow-unauthenticated --region us-central1 --quiet --project $PROJECT_ID
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
