version: "3.6"

services:
  # Web app #
  web:
    image: node:14
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - ml.db
    volumes:
      - .:/app
    command:
      bash -c "npm install && npm start"

  # Database
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ml.db"
      POSTGRES_USER: "un.aitist"
      POSTGRES_PASSWORD: "un.aitist"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
